//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciberstyleAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ciberstyleEntities : DbContext
    {
        public ciberstyleEntities()
            : base("name=ciberstyleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Reclamos> Reclamos { get; set; }
    
        public virtual ObjectResult<compradetalle_Result> compradetalle(Nullable<int> idpago)
        {
            var idpagoParameter = idpago.HasValue ?
                new ObjectParameter("idpago", idpago) :
                new ObjectParameter("idpago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<compradetalle_Result>("compradetalle", idpagoParameter);
        }
    }
}
